import type { Metadata } from 'next'
import {
  Amiri,
  Great_Vibes,
  Cormorant_Garamond,
  Poppins,
  Sacramento,
  Reem_Kufi,
} from 'next/font/google'
import './globals.css'

// ─── Fonts ────────────────────────────────────────────────────────
// Each font returns a `variable` CSS class (e.g. --font-amiri).
// These class names are generated by Next.js CSS Modules and can
// differ slightly between SSR and client hydration in Next.js 16
// (double-underscore vs single-underscore suffix).
// suppressHydrationWarning on <html> is the official fix for this.
const amiri = Amiri({
  subsets: ['arabic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-amiri',
  display: 'swap',
})

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-great-vibes',
  display: 'swap',
})

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-cormorant',
  display: 'swap',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-poppins',
  display: 'swap',
})

const sacramento = Sacramento({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-sacramento',
  display: 'swap',
})

const reemKufi = Reem_Kufi({
  subsets: ['arabic', 'latin'],
  weight: ['400', '500', '600'],
  variable: '--font-reem-kufi',
  display: 'swap',
})

// ─── Metadata ─────────────────────────────────────────────────────
export const metadata: Metadata = {
  title: 'Eid Mubarak — Arfa Siddiqui 🌙',
  description:
    'A cinematic Eid Mubarak dedication for Arfa Siddiqui — crafted with love by Aliyan Ahmed Siddiqui.',
  keywords: ['Eid Mubarak', 'Arfa Siddiqui', 'Aliyan Ahmed Siddiqui', 'Eid 2026'],
  authors: [{ name: 'Aliyan Ahmed Siddiqui' }],
  openGraph: {
    title: 'Eid Mubarak — Arfa Siddiqui 🌙',
    description: 'A cinematic Eid Mubarak dedication crafted with love.',
    type: 'website',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Eid Mubarak — Arfa Siddiqui 🌙',
    description: 'A cinematic Eid Mubarak dedication crafted with love.',
  },
  manifest: '/manifest.json',
}

// ─── Layout ───────────────────────────────────────────────────────
export default function RootLayout({ children }: { children: React.ReactNode }) {
  const fontVars = [
    amiri.variable,
    greatVibes.variable,
    cormorant.variable,
    poppins.variable,
    sacramento.variable,
    reemKufi.variable,
  ].join(' ')

  return (
    /*
     * suppressHydrationWarning on <html> is the correct, officially
     * recommended fix (Next.js docs, React docs) for two cases:
     *
     *  1. next/font CSS Module class names can have __ vs _ suffix
     *     differences between SSR output and client reconciliation
     *     (Turbopack hash inconsistency — Next.js 15+/16+).
     *
     *  2. Any theme library (next-themes, etc.) that adds/changes the
     *     `dark` class client-side after reading localStorage will
     *     also cause a mismatch without this attribute.
     *
     * Important: suppressHydrationWarning is SCOPED — it only
     * suppresses the warning on <html> itself, never on child nodes.
     * It does NOT hide real bugs in your app's content.
     *
     * Since this site is dark-only (no theme toggle), `dark` is
     * hardcoded server-side → zero FOUC. suppressHydrationWarning
     * purely handles the font CSS Module hash edge case.
     */
    <html
      lang="en"
      dir="ltr"
      className={`dark ${fontVars}`}
      suppressHydrationWarning
    >
      <head>
        <meta name="theme-color" content="#04040f" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
      </head>
      <body className="bg-midnight text-cream overflow-x-hidden antialiased">
        {children}
      </body>
    </html>
  )
}
